// Original practice items, not official College Board questions or frequency predictions.
const WORDS = [
['equivocal','ambiguous or inconclusive','equ = equal; vox = voice. The history suggests more than one possible interpretation.','unequivocal,tenable,irrelevant',
'Although two assays detected a change, a third did not, and none could distinguish a treatment effect from ordinary fluctuation. The team therefore characterized the evidence as _____.','Conflicting results and competing interpretations make the evidence inconclusive, rather than unambiguous.',
'The critic praised the exhibition’s ambition while withholding any judgment about whether it succeeded. Her assessment remained _____, permitting both favorable and unfavorable readings.','The assessment permits different readings; it is not an unambiguous verdict.'],
['qualify','limit or modify a claim','Memory cue: add a qualification, such as “only under these conditions.” This is not the “be eligible” sense.','refute,corroborate,supplant',
'The survey supports the view that remote work increases satisfaction. However, its authors _____ that conclusion by noting that the effect was confined to employees who could choose their schedules.','The authors restrict where the claim applies; they do not show that it is false.',
'A historian accepts that trade expanded after the treaty, but points out that expansion had begun several years earlier. This observation serves to _____ the claim that the treaty alone caused the increase.','The observation limits the exclusive causal claim without denying that the treaty contributed.'],
['specious','apparently sound but actually misleading','Memory cue: a persuasive surface can conceal faulty reasoning. Do not infer the meaning from “species.”','plausible,tenable,unequivocal',
'The essay cites a genuine correlation and presents it as proof of causation, neglecting a third variable that explains both trends. Its central argument is _____ despite its appearance of statistical rigor.','The argument looks sound but makes an invalid causal inference.',
'A company calls its device economical because it costs less to purchase, omitting unusually high maintenance expenses. The claim is _____ when interpreted as a statement about total ownership cost.','The selective comparison gives a misleading impression of total cost.'],
['contingent','dependent on a condition','Memory cue: contingent on = dependent on. In other contexts, a contingent can be a group of people.','inevitable,reciprocal,immutable',
'The model predicts population growth only if winter temperatures remain above a specified threshold. Its prediction is therefore _____ on an environmental condition that the researchers cannot guarantee.','The prediction depends on the temperature condition; growth is not inevitable.',
'The archive will receive the grant if it first secures matching funds. Because the award is _____ on that additional financing, the director cannot yet include it in the operating budget.','The award depends on another source of financing.'],
['attenuate','reduce the strength or intensity of','Memory cue: attenuation is weakening, not complete removal.','eliminate,exacerbate,augment',
'Adding a porous layer to the wall reduced the amplitude of transmitted sound, but conversation remained audible. The layer could _____ the noise without fully blocking it.','Reduced amplitude indicates weakening; continued audibility rules out elimination.',
'The essay’s initial claim was sweeping. Subsequent exceptions _____ its force, leaving a narrower argument that applied to only a few of the cases under discussion.','Exceptions weaken the force of the claim; they do not strengthen it.'],
['supplant','take the place of; replace','Memory cue: the newer thing occupies the older thing’s role.','augment,corroborate,mitigate',
'For decades, technicians relied on chemical staining to identify the cells. A new imaging method eventually came to _____ staining as the laboratory’s standard procedure; staining was no longer used.','The new method takes over the old method’s role.',
'The poet initially borrowed the conventions of pastoral verse. Later, urban imagery came to _____ the rural settings that had once dominated her work.','Urban settings replace the formerly dominant rural settings.'],
['corroborate','support with independent evidence','Memory cue: another source supports the same account. Support need not be absolute proof.','refute,qualify,supplant',
'The diary places the expedition at the river in June. An independently dated shipping record places its supplies there that same month, helping to _____ the diary’s account.','An independent record supports the diary’s timeline.',
'A model predicts a previously unobserved spectral line. When an instrument detects a line at the predicted wavelength, the observation helps _____ the model without establishing that all its assumptions are correct.','The observation supports the prediction; the passage explicitly limits its reach.'],
['substantiate','establish or support with evidence','Memory cue: give a claim evidentiary substance.','assert,elucidate,undermine',
'The analyst does more than state that the policy reduced delays: she provides matched before-and-after records and explains how competing causes were controlled. These data _____ her claim.','The analyst supplies evidence rather than merely making an assertion.',
'An attribution to the painter remained conjectural until pigment analysis and purchase records linked the canvas to his workshop. Together, the findings helped _____ the attribution.','The new evidence provides a factual basis for the attribution.'],
['undermine','weaken the basis or credibility of','Memory cue: weaken the support beneath a claim. Weakening does not necessarily disprove it.','refute,substantiate,elucidate',
'The hypothesis depends on the assumption that every sample was collected before rainfall. Records showing that some were collected afterward _____ the hypothesis, though they do not by themselves establish an alternative.','The records weaken an assumption without conclusively disproving the hypothesis.',
'The critic’s interpretation rests on a supposedly consistent narrative voice. Several unexplained shifts in that voice _____ the interpretation’s foundation.','The shifts weaken the foundation of the interpretation.'],
['refute','show that a claim is false','Memory cue: a decisive contradiction is stronger than doubt alone.','qualify,undermine,corroborate',
'The claim was that no member of the species could survive freezing. A carefully verified instance of survival was enough to _____ that universal claim.','One verified counterexample disproves the claim about every member.',
'A biographer asserted that the author never visited Lisbon. Authenticated letters written there by the author _____ this assertion.','The letters directly contradict and disprove the claim of never visiting.'],
['ambivalent','having conflicting feelings about something','ambi = both; valere = be strong. Think of competing attitudes, not absence of interest.','indifferent,skeptical,dogmatic',
'The reviewer welcomed the play’s departure from convention but regretted the loss of emotional intimacy that accompanied it. Her response to the innovation was _____.','She has both a favorable and an unfavorable reaction.',
'The researcher wanted the promotion’s intellectual freedom yet dreaded its administrative duties. His attitude toward the offer was _____ rather than simply enthusiastic or hostile.','He feels pulled in opposing directions.'],
['indifferent','unconcerned; having little interest','Memory cue: neither invested in nor troubled by the outcome.','ambivalent,skeptical,circumspect',
'Unlike colleagues who passionately supported or opposed the redesign, the archivist expressed no preference and devoted no attention to the debate. She was _____ to its outcome.','She lacks concern; the passage does not describe conflicting feelings.',
'The experiment found that the insects approached either colored target equally, showing no preference even after repeated trials. With respect to color, their behavior appeared _____.','No preference indicates indifference in this particular respect.'],
['circumspect','cautious; attentive to possible consequences','circum = around; spect = look. Look around before committing.','dogmatic,indifferent,unequivocal',
'Aware that the data could influence public policy, the authors emphasized uncertainty and declined to extend their findings beyond the sampled region. Their presentation was _____.','They carefully limit claims in view of the consequences.',
'The curator did not immediately accept the newly offered manuscript. She first requested provenance records and specialist opinions, taking a _____ approach to the acquisition.','Checking before committing shows caution, not lack of interest.'],
['dogmatic','asserting beliefs with rigid certainty','Memory cue: unwilling to revise an asserted position.','circumspect,tentative,pragmatic',
'Even after several predictions failed, the theorist insisted that his framework could not be mistaken and refused to consider revisions. His stance was _____.','His certainty persists despite evidence against his predictions.',
'The critic declared that only one form could count as poetry, dismissing counterexamples without examining them. This _____ position left little room for debate.','The critic rigidly asserts an exclusive belief.'],
['pragmatic','guided by practical considerations','Memory cue: ask what works under the actual constraints.','dogmatic,specious,arbitrary',
'Rather than insist on an ideal but unaffordable restoration, the committee chose a less extensive repair that would keep the bridge usable. Its decision was _____.','The choice prioritizes a workable result under financial constraints.',
'The linguist used a simplified notation because the audience needed to apply the analysis in classrooms, even though a fuller notation was theoretically preferable. The choice was _____.','Practical usefulness guides the choice.'],
['disparate','markedly different in character','Memory cue: genuinely different kinds, rather than merely separate instances.','analogous,compatible,reciprocal',
'The collection brings together a medieval legal document, an experimental film, and a modern botanical sketch. The curator traces a shared theme across these otherwise _____ works.','The works differ strongly in form, period, and subject.',
'A researcher combines oral histories with satellite measurements, arguing that these _____ sources illuminate different aspects of the same migration.','The sources differ markedly in their nature and what they measure.'],
['analogous','similar in a relevant respect','Memory cue: an analogy compares a particular relationship, not complete identity.','identical,disparate,incongruous',
'A city’s roads and an organism’s blood vessels differ in material and purpose, but both distribute resources through branching networks. Their structures are _____ in this respect.','The branching distribution relationship is similar; the structures are not identical.',
'The novelist’s recurring phrase functions like a musical refrain: each return changes how the surrounding material is understood. The two devices have _____ roles.','The devices play comparable roles in organizing interpretation.'],
['incongruous','out of keeping with the surrounding context','Memory cue: it does not fit the setting or pattern.','anomalous,compatible,analogous',
'The memorial’s restrained design invites quiet contemplation. A flashing advertisement installed at its center would be _____ with that solemn atmosphere.','The advertisement would clash with the atmosphere, not merely be statistically unusual.',
'The narrator maintains a formal, measured tone throughout the chapter. An abrupt slang-filled aside seems _____ with the voice established in the surrounding paragraphs.','The aside does not fit the established voice.'],
['reciprocal','mutual; involving corresponding exchanges','Memory cue: each side gives or acts in return.','contingent,disparate,arbitrary',
'Each library grants the other’s members borrowing privileges. Because the arrangement benefits and obligates both institutions in corresponding ways, it is _____.','Each institution extends the same privilege to the other.',
'The two species exchange resources: one supplies sugars, while the other supplies minerals. Their relationship involves _____ benefits.','Benefits move in both directions.'],
['compatible','able to coexist without conflict','Memory cue: can both claims or systems be true or work together?','identical,analogous,incongruous',
'One study shows that average income rose; another shows that income inequality increased. The findings are _____ because rising averages need not imply equal gains.','Both findings can be true; they do not make identical claims.',
'The historian argues that institutional rules constrained the leader’s choices, while a colleague emphasizes the leader’s creativity within those limits. These interpretations are _____ rather than mutually exclusive.','Constraints and creative choices can coexist.'],
['plausible','apparently reasonable or believable','Memory cue: possible and credible is weaker than proven.','substantiated,inevitable,specious',
'The proposed mechanism agrees with known chemistry and could explain the pattern. Without direct measurements, however, it remains a _____ explanation rather than an established one.','The explanation is reasonable but lacks confirming evidence.',
'The broken seal offers a _____ explanation for the missing contents, but investigators have not ruled out an error in the original inventory.','The explanation could be true; an alternative remains.'],
['tenable','capable of being defended','ten = hold, as in maintain. A position can “hold up” under scrutiny.','immutable,specious,unequivocal',
'Although a new objection requires a minor revision, it does not contradict the argument’s central premises. The philosopher maintains that the position remains _____.','The position can still be defended despite the objection.',
'The reading accounts for the poem’s imagery and resolves an apparent contradiction without ignoring any lines. It is therefore a _____ interpretation, even if other readings are possible.','The interpretation withstands scrutiny without claiming exclusive certainty.'],
['arbitrary','not based on a consistent reason or rule','Memory cue: a selection without a relevant principle.','pragmatic,contingent,reciprocal',
'The researchers selected a cutoff simply because it was a round number, offering no theoretical or empirical justification. The cutoff was _____.','No relevant reason supports the threshold.',
'Two applications with identical qualifications received different outcomes, and the committee could identify no criterion explaining the difference. The decision appeared _____.','The outcomes lack a consistent stated basis.'],
['coherent','logically connected and consistent','co = together; haerere = stick. The pieces hold together.','succinct,plausible,unequivocal',
'The essay connects each example to the same central claim and explains how apparently conflicting findings can coexist. Its argument is _____, though considerably longer than necessary.','Logical connection and consistency are the focus; length rules out succinctness.',
'Previously isolated observations are now linked by a framework whose assumptions do not contradict one another. The framework provides a _____ account of the phenomenon.','The observations form a consistent, connected account.'],
['paradoxical','apparently contradictory, yet potentially true','para = beyond or contrary; doxa = opinion. Think of an apparent contradiction.','incongruous,arbitrary,analogous',
'Restrictions designed to reduce traffic made driving more appealing by eliminating congestion, ultimately attracting more cars. This _____ outcome reversed the policy’s intended effect through its own success.','Reducing traffic leads to more traffic through the mechanism described.',
'The restoration preserved the building’s original appearance by replacing nearly all its original materials. The claim that replacement achieved preservation is _____ at first glance.','Replacement and preservation appear contradictory, though the distinction explains them.'],
['implicit','suggested without being directly stated','im/in = in; plic = fold. Think “folded into” the text.','explicit,equivocal,superfluous',
'The narrator never says that the siblings distrust each other, but their guarded replies and concealed letters make that distrust _____ in the scene.','The distrust is conveyed indirectly through behavior.',
'No rule expressly forbids junior members from speaking first. Nevertheless, the seating order and repeated examples communicate an _____ expectation that senior members will begin.','The expectation is communicated without direct statement.'],
['explicit','directly stated or clearly expressed','ex = out; plic = fold. Think “unfolded” or made overt.','implicit,nuanced,tentative',
'Earlier guidelines merely hinted that attribution was expected. The revised guidelines make the requirement _____ by stating, “Every quotation must identify its source.”','The requirement is now directly stated.',
'The novelist usually leaves motives for readers to infer. Here, however, a character gives an _____ account of her reasons, listing them one by one.','The character states her reasons directly.'],
['nuanced','attentive to subtle distinctions','Memory cue: shades of meaning instead of an all-or-nothing judgment.','equivocal,dogmatic,verbose',
'Rather than classify the policy as wholly successful or wholly unsuccessful, the analysis distinguishes its effects by region, time period, and income level. It offers a _____ assessment.','The analysis makes fine distinctions; it is not merely uncertain.',
'The translator preserves both admiration and irony in a phrase that simpler renderings treat as straightforward praise. Her version conveys a more _____ attitude.','The version preserves multiple subtle aspects of the attitude.'],
['unequivocal','clear and unambiguous','un = not; equivocal = open to different interpretations.','tentative,equivocal,nuanced',
'The committee had previously issued guarded statements. Its latest announcement is _____: it rejects the proposal without conditions or reservations.','The rejection leaves no ambiguity.',
'All three independent measurements point to the same result, and no alternative interpretation fits the recorded values. Within the tested conditions, the evidence is _____.','Agreement and exclusion of alternatives support an unambiguous conclusion within the stated scope.'],
['salient','especially noticeable or relevant','Memory cue: the feature that stands out for this particular question.','substantial,negligible,superfluous',
'The two populations differ in many ways, but only their nesting behavior bears directly on the hypothesis under investigation. That behavior is the most _____ distinction for the study.','Relevance to the hypothesis, not size alone, makes it salient.',
'The historian lists several causes of the dispute but devotes most of the analysis to water rights, the factor that best explains when tensions intensified. Water rights are especially _____ to her account.','Water rights stand out as particularly explanatory.'],
['anomalous','departing from an expected pattern','Memory cue: an anomaly is an exception to the usual pattern.','incongruous,sporadic,negligible',
'Every recorded eclipse in the series matched the model except one, whose timing differed substantially despite verified measurements. That observation was _____.','One observation departs from the established pattern.',
'Most manuscripts in the archive use the same spelling convention. A single otherwise comparable manuscript consistently uses a different convention, making it _____ within the collection.','The manuscript is an exception relative to comparable examples.'],
['negligible','too small to have much practical significance','Memory cue: small enough to neglect for the purpose at hand; not necessarily zero.','nonexistent,substantial,sporadic',
'The second coating improved efficiency by 0.01 percent, an amount far below ordinary measurement variation. For practical applications, the improvement was _____.','The effect is nonzero but too small to matter for the stated purpose.',
'A delivery fee of a few cents had a _____ effect on the total cost of equipment worth several thousand dollars.','The fee contributes very little to the relevant total.'],
['disproportionate','out of proportion to a relevant baseline','Memory cue: compare a share with the share you would expect.','substantial,reciprocal,negligible',
'Although the district contains only 5 percent of the city’s residents, it receives 40 percent of its infrastructure funding. Its share of funding is _____ relative to its population.','The share is out of proportion to the specified population baseline.',
'A small component accounted for most system failures. Its influence on reliability was _____ to its size within the machine.','The component’s effect is unusually large relative to its size.'],
['pervasive','spread throughout an area or system','Memory cue: permeates many parts of the whole.','sporadic,transient,negligible',
'The assumptions are not confined to the introduction; they shape the sampling, calculations, and interpretation throughout the report. Their influence is _____.','The influence extends through many parts of the report.',
'Investigators found the same bias in hiring, promotion, and assignment practices across nearly every department. The bias was _____ within the institution.','The bias is spread throughout the institution.'],
['sporadic','occurring irregularly or occasionally','Memory cue: scattered occurrences; this says little about how long each lasts.','transient,pervasive,immutable',
'The signal did not appear at regular intervals. It emerged on a few widely separated occasions, with long periods of silence between them. Its occurrence was _____.','Irregular, scattered occurrences establish the meaning.',
'The journal published translations in some years but none in many others, without a fixed schedule. Its translation program was _____.','The publications occur occasionally and irregularly.'],
['transient','lasting only a short time','trans = across; memory cue: passing through. Distinguish duration from frequency.','sporadic,enduring,immutable',
'The treatment caused an initial rise in temperature, but readings returned to baseline within minutes and stayed there. The increase was _____.','The effect’s short duration is the key.',
'The exhibition briefly revived interest in the artist, but attendance and publications soon returned to their previous levels. The revival proved _____.','The renewed interest lasted only briefly.'],
['intractable','difficult to manage or resolve','in = not; tract = draw or pull. Think “not easily handled.”','immutable,transient,negligible',
'Despite decades of revised models and improved measurements, the discrepancy has resisted every proposed explanation. It remains an _____ problem, though researchers have not ruled out a future solution.','The problem is difficult to resolve, not necessarily permanently unchangeable.',
'Negotiators resolved most disagreements quickly, but the boundary question resisted repeated compromises. That issue proved _____.','Repeated failure to reach resolution indicates difficulty.'],
['malleable','capable of being shaped or modified','Memory cue: like material that can be hammered into a different shape; opinions can be malleable too.','resilient,immutable,enduring',
'Unlike the rigid categories of the earlier framework, the new categories can be reshaped as additional evidence emerges. They are intentionally _____.','The categories can change shape or definition.',
'The curator’s interpretation changed substantially after each new discovery. Rather than fixed, it was _____ in response to evidence.','The interpretation is readily modified.'],
['resilient','able to recover after disruption','Memory cue: rebounds after stress; resilience does not mean remaining unaffected.','immutable,malleable,transient',
'The ecosystem suffered considerable damage during the drought but recovered its earlier diversity after rainfall returned. Its recovery demonstrated that it was _____.','Recovery after damage is resilience; it was not immune to change.',
'The organization lost funding and suspended several programs, yet rebuilt them within a year. Its response showed a _____ capacity to recover.','The emphasis is recovery after a setback.'],
['immutable','not capable of being changed','im/in = not; mut = change, as in mutation.','intractable,resilient,enduring',
'In the model, the value is treated as _____: no permitted operation can alter it, even when other parameters are adjusted.','The model explicitly excludes any change.',
'The inscription was preserved in a digital record designed to prevent any subsequent alteration. Within that system, the recorded text is _____.','The text cannot be altered within the specified system.'],
['mitigate','make less severe','Memory cue: lessen a harm without necessarily removing it.','eliminate,exacerbate,precipitate',
'The barriers could not prevent every flood, but they reduced the depth and extent of inundation. They helped _____ the damage.','The barriers lessen damage rather than remove all flooding.',
'The editor retained a negative assessment but added acknowledgment of the author’s achievements to _____ the harshness of the review.','The acknowledgment makes the criticism less severe.'],
['exacerbate','make an existing problem worse','Memory cue: aggravate a difficulty that already exists.','precipitate,mitigate,attenuate',
'The valley was already experiencing water shortages. Diverting the remaining stream to a new factory would _____ the scarcity.','The diversion worsens an existing shortage.',
'The dispute had already strained relations. An accusatory public statement served to _____ those tensions.','Existing tensions become more severe.'],
['precipitate','cause to occur suddenly or sooner','Memory cue: an event triggers an outcome. In chemistry, precipitate has a different sense.','exacerbate,mitigate,corroborate',
'The negotiations had continued without a deadline for months. An unexpected withdrawal of funding helped _____ their collapse, which followed within days.','The withdrawal triggers the collapse rather than merely intensifying an existing collapse.',
'The institution had postponed a leadership transition for years. The director’s sudden resignation _____ a transition that otherwise would have happened much later.','The resignation causes the transition to occur sooner.'],
['augment','increase or add to','Memory cue: add capacity, quantity, or force.','supplant,attenuate,qualify',
'The new photographs do not replace the written records. Instead, they _____ the archive by adding evidence of buildings the records mention only briefly.','The photographs add to the existing archive.',
'The orchestra retained its usual instruments but added extra percussion to _____ the intensity of the final movement.','Additional instruments increase intensity.'],
['elucidate','make something clear; explain','luc = light, as in lucid. Shed light on something.','substantiate,obscure,assert',
'The diagrams do not supply additional evidence for the theory. Rather, they _____ its mechanism by showing each intermediate step in a form readers can follow.','The diagrams explain how it works, rather than adding evidence that it is true.',
'The scholar compares two translations to _____ a difficult metaphor, showing how its images relate to one another.','The comparison clarifies meaning.'],
['concede','acknowledge a point, often reluctantly','Memory cue: grant a point to another side while potentially retaining your main argument.','refute,obscure,supplant',
'The critic continues to oppose the policy but does _____ that it reduced waiting times, a benefit she had previously denied.','She acknowledges an opposing point without endorsing the entire policy.',
'Although the historian disputes the proposed date, he must _____ that the newly discovered reference is earlier than any previously known example.','He acknowledges a fact while maintaining a broader disagreement.'],
['redundant','unnecessarily repeating or duplicating something','Memory cue: already supplied elsewhere; duplicated function or information.','tentative,succinct,implicit',
'The final sentence repeats the preceding sentence’s claim without adding evidence, explanation, or qualification. In this respect, it is _____.','The sentence repeats information without adding anything; succinct would describe brief, efficient expression.',
'The form requests the same identification number in three fields, each serving the same purpose. Two of those requests are _____.','The requests duplicate an already supplied piece of information.'],
['superfluous','unnecessary; beyond what is needed','Memory cue: extra material can be unnecessary without repeating anything.','redundant,salient,explicit',
'A detailed account of the author’s breakfast neither repeats earlier material nor contributes to the essay’s argument. The editor considers it _____.','The detail is unnecessary without being repetitive.',
'The simplified procedure requires only two measurements. A third measurement adds no useful information and duplicates neither of the first two, making it _____.','It is extra and unnecessary; the text excludes duplication.']
].map((a,id)=>({id,word:a[0],meaning:a[1],root:a[2],distractors:a[3].split(','),variants:[{text:a[4],clue:a[5]},{text:a[6],clue:a[7]}]}));
const EXTRA = {inevitable:'certain to happen',identical:'exactly the same',nonexistent:'not present at all',enduring:'lasting',substantial:'considerable in amount',succinct:'brief and clear',verbose:'using more words than needed',skeptical:'doubtful',irrelevant:'unrelated to the matter',eliminate:'remove completely',assert:'state confidently',obscure:'make less clear'};
EXTRA.tentative='provisional; not yet certain';EXTRA.substantiated='supported or established with evidence';
EXTRA.provisional='temporary or subject to later confirmation';
EXTRA.ostensible='apparent or stated, without certainty that it is actual';
EXTRA.impartial='fair; not favoring one side';
EXTRA.sincere='honest and genuine';
EXTRA.comprehensive='covering all relevant aspects';
EXTRA.elaborate='develop in more detail';
EXTRA.praise='express approval of';
EXTRA.predictable='able to be anticipated';
EXTRA.orthodox='conforming to established beliefs or practices';
EXTRA.irrefutable='not able to be disproved';
EXTRA.diffident='lacking self-confidence';
const STRETCH=[
['inchoate','only partly formed or developed','Memory cue: a beginning that has not yet taken a clear shape.','coherent,immutable,explicit',
'The earliest notebook contains fragments of a plan but no settled categories, sequence, or organizing principle. It records an _____ proposal that became more fully developed in later drafts.','The proposal has begun to form but lacks a developed structure.',
'The coalition shared a general dissatisfaction with the law, yet had not agreed on specific objectives or methods. Its agenda remained _____.','General intentions exist, but a clear agenda has not yet taken shape.'],
['ostensible','apparent or stated, without assurance it is actual','Memory cue: the stated purpose may differ from the actual purpose.','explicit,implicit,substantiated',
'The meeting’s _____ purpose was to discuss routine scheduling. Private correspondence, however, reveals that its organizers chiefly intended to secure support for a controversial appointment.','The stated purpose differs from the organizers’ actual primary intention.',
'The report describes cost savings as the _____ reason for the closure, while acknowledging that undisclosed strategic considerations may have mattered more.','The reason is presented as the reason, but its actual primacy is uncertain.'],
['disinterested','impartial; free from a personal stake','Memory cue: disinterested can mean impartial. Uninterested means lacking interest. Check the intended sense.','indifferent,ambivalent,dogmatic',
'The reviewer followed the competition closely but had no connection to any entrant and no financial stake in the result. The organizers valued her _____ judgment.','She is engaged but impartial; indifference would describe lack of concern.',
'The mediator was attentive to both parties’ arguments and stood to gain nothing from either outcome. That lack of personal interest enabled a _____ assessment.','Absence of a personal stake supports impartial judgment, not inattentiveness.'],
['disingenuous','not candid; pretending to be more sincere or uninformed than one is','Memory cue: a performance of innocence or sincerity can conceal what someone knows.','sincere,tentative,equivocal',
'The executive claimed not to understand the objection, although earlier emails showed that she had described it accurately to colleagues. Her professed confusion was _____.','She pretends not to understand something she demonstrably understands.',
'The author portrays his selection of examples as neutral while privately admitting that he omitted every counterexample. His description of the selection process is _____.','The description conceals deliberate selectivity behind a claim of neutrality.'],
['perfunctory','done routinely with little care or interest','Memory cue: going through the motions. Brief work is not necessarily careless.','succinct,assiduous,circumspect',
'The inspector checked each box on the form without examining the equipment the boxes referred to. The resulting inspection was _____ rather than thorough.','Completing the routine superficially without examining the equipment shows lack of care.',
'The review repeated the publisher’s summary and offered no independent evaluation, suggesting that the critic’s engagement with the book had been _____.','The review shows superficial, routine engagement rather than careful evaluation.'],
['assiduous','showing sustained, careful effort','Memory cue: diligent attention over time.','perfunctory,sporadic,arbitrary',
'For several years, the archivist compared every new attribution with purchase records, correspondence, and material evidence. Her _____ work eventually resolved many longstanding uncertainties.','Sustained, careful checking demonstrates diligence.',
'The translator revised difficult passages repeatedly and consulted specialists whenever a term was unclear. This _____ attention distinguished the final version from a hurried draft.','Repeated revision and consultation show sustained care.'],
['obviate','make unnecessary','Memory cue: remove the need for something; distinguish this from simply forbidding it.','preclude,augment,necessitate',
'The automated system supplied the exact measurements technicians had previously taken by hand. It therefore served to _____ manual measurement, although technicians remained free to perform it.','The system makes manual work unnecessary without making it impossible.',
'A sufficiently detailed index would _____ the need to search every folder individually, because it would identify the relevant folders in advance.','The index removes the need for an exhaustive search.'],
['preclude','prevent; rule out the possibility of','pre = before; clud = close. Think of closing off a possibility.','obviate,mitigate,qualify',
'The samples were irreversibly destroyed during analysis. Their destruction would _____ any later attempt to repeat the test on those same samples.','The later test is impossible because the samples no longer exist.',
'Because the two events were scheduled at exactly the same time in distant cities, attending either in person would _____ attending the other in person.','The stated constraints rule out attending both.'],
['engender','bring about; give rise to','Memory cue: generate a response, feeling, or condition.','corroborate,elucidate,attenuate',
'The policy did not address an existing dispute; instead, its unequal application helped _____ resentment among groups that had previously cooperated.','The unequal application brings resentment into being.',
'By exposing contradictions that readers had overlooked, the essay was able to _____ a new debate about the archive’s reliability.','The essay gives rise to a debate rather than simply supporting an existing claim.'],
['repudiate','reject or disavow','Memory cue: rejecting a claim is not automatically proof that it is false.','refute,qualify,substantiate',
'The researcher chose to _____ the interpretation attributed to her, stating that she had never endorsed it. She offered no evidence bearing on whether the interpretation itself was correct.','She disavows an interpretation; she does not disprove it.',
'The organization voted to _____ its former policy, formally rejecting the principles on which that policy had been based.','The organization rejects and disavows its previous position.'],
['esoteric','understood by a small specialized group','Memory cue: specialized access to understanding, not necessarily secrecy.','ubiquitous,explicit,prosaic',
'The treatise assumes familiarity with notation and debates known only to a small circle of specialists. Its subject matter is _____ even though the volume is publicly available.','Understanding is restricted by specialized knowledge, not by access to the book.',
'The critic contrasts the novelist’s widely accessible dialogue with _____ references that only readers versed in medieval theology are likely to recognize.','The references require specialized knowledge held by a limited audience.'],
['prosaic','ordinary; lacking imaginative or poetic distinction','Memory cue: ordinary and unromantic, even when the writing is not literally prose.','esoteric,anomalous,nuanced',
'Legends attribute the structure’s unusual shape to celestial symbolism. Excavation points to a more _____ explanation: the builders adapted it to the available plot of land.','A practical, ordinary explanation contrasts with the imaginative legend.',
'The poet transforms _____ objects such as receipts and kitchen utensils into subjects of striking imagery.','Everyday ordinary objects are elevated by the poetry.'],
['erratic','unpredictably irregular in behavior or movement','Memory cue: unpredictable variation, rather than simply infrequent occurrence.','sporadic,predictable,transient',
'The instrument operated continuously, but its readings swung unpredictably between high and low values. Its output was _____, not merely intermittent.','Unpredictable variation during continuous operation distinguishes this from sporadic occurrence.',
'The actor’s delivery shifted without an apparent pattern from nearly inaudible speech to abrupt shouting. The critic described the performance as _____.','The delivery varies unpredictably in manner.'],
['ephemeral','lasting a very short time','Memory cue: brief-lived. Duration differs from rarity or frequency.','sporadic,enduring,pervasive',
'The digital artwork generated an image that vanished seconds later and could not be revisited. Its deliberately _____ nature made each viewing temporary.','The image exists only briefly.',
'Public attention surged immediately after the announcement but disappeared within a day. The surge was _____ despite its initial intensity.','High intensity does not prevent the surge from being very short-lived.'],
['provisional','temporary or subject to later confirmation','Memory cue: usable for now, with a later decision still required.','immutable,unequivocal,arbitrary',
'The catalog assigned the work to the painter pending pigment analysis and expert review. The attribution was _____ and could be revised when those assessments were complete.','The attribution is subject to later confirmation or revision.',
'The board adopted an interim rule that would expire unless ratified at its next meeting. The rule had _____ status.','The rule applies temporarily pending ratification.'],
['presuppose','take as an assumption in advance','pre = before. A premise can be assumed without having been demonstrated.','substantiate,infer,refute',
'The argument treats every reported observation as accurate without independently checking any of them. It must therefore _____ the reliability of the reports rather than establish it.','Reliability is assumed at the outset, not supported by evidence.',
'The proposed explanation would work only if the two populations had never interacted. Its logic must therefore _____ their historical isolation, a condition the available records do not confirm.','The explanation assumes a condition that remains unverified.'],
['inimical','hostile or harmful to something','Memory cue: conditions can work against a goal without anyone intending harm.','compatible,beneficial,indifferent',
'Repeated freezes destroyed seedlings before they could establish roots. These conditions were _____ to the restoration effort, regardless of the care taken by volunteers.','The conditions harm and work against the effort.',
'The institution required every interpretation to receive prior approval, a restriction critics considered _____ to independent inquiry.','The restriction works against independent inquiry.'],
['commensurate','corresponding in size or degree; proportionate','com = together; mensur = measure. Compare an amount to a relevant measure.','disproportionate,identical,negligible',
'The committee scaled each grant to the documented cost of the proposed work. It aimed to make funding _____ with actual need rather than equal for every applicant.','The amount corresponds to need; equal amounts are not required.',
'Reviewers argued that the sweeping conclusion was not _____ with the limited evidence on which it rested.','The conclusion’s scope should correspond to the strength and scope of the evidence.'],
['reconcile','bring into agreement or show to be compatible','Memory cue: resolve an apparent conflict between findings or positions.','refute,elucidate,supplant',
'One survey reports growing demand, while another reports falling sales. By showing that supply shortages prevented purchases, the analyst is able to _____ the seemingly conflicting findings.','The explanation shows how both findings can be true.',
'The historian seeks to _____ two accounts that appear inconsistent, demonstrating that they describe different stages of the same event.','Different stages allow the accounts to coexist without contradiction.'],
['equivocate','use ambiguous language to avoid committing','Memory cue: equivocal describes ambiguity; equivocate describes speaking evasively.','qualify,concede,elucidate',
'Asked whether he supported the proposal, the official chose to _____, offering statements that could be read as either endorsement or opposition rather than giving a definite answer.','The official uses ambiguity to avoid commitment.',
'The witness repeatedly replaced direct answers with phrases whose meanings shifted depending on the listener’s interpretation. Counsel objected that the witness continued to _____.','The witness speaks evasively rather than answering directly.'],
['deleterious','harmful in effect','Memory cue: describes the harmful consequence, whether intended or not.','beneficial,negligible,efficacious',
'Exposure to the compound impaired cell growth even at low concentrations. The researchers therefore described its effect on the cells as _____.','Impaired growth is a harmful effect.',
'The new cleaning treatment removed stains but also weakened the paper’s fibers. Its _____ effect on the underlying material outweighed its cosmetic benefit.','Damage to the material is harmful despite the visible benefit.'],
['efficacious','effective in producing the intended result','Memory cue: efficacy asks whether the intervention achieves its goal.','pragmatic,plausible,deleterious',
'The device was expensive and difficult to operate, but repeated trials showed that it reliably achieved the intended reduction in pollutants. In that respect, it was _____.','Success at the intended task establishes efficacy, despite practical drawbacks.',
'Controlled trials showed that the intervention consistently improved the targeted outcome. This evidence established that the intervention was _____ under the tested conditions.','The intervention produces its intended effect within the stated scope.'],
['ubiquitous','present everywhere or seemingly everywhere','Memory cue: ubi = where. Stronger scope than occasional or merely widespread.','pervasive,sporadic,esoteric',
'Unlike earlier tools found only in specialist laboratories, the new device appeared in virtually every school, office, and household the survey examined. It had become _____ across these settings.','Presence in virtually every surveyed setting supports this broad scope.',
'The symbol appears on nearly every page of the manuscript, in headings, diagrams, notes, and body text. Within that document, it is _____.','The passage stresses presence virtually everywhere within a defined scope.'],
['diffident','lacking self-confidence; hesitant from insecurity','dis = away / not; fid = trust. Think of insufficient trust in one’s own ability.','circumspect,indifferent,dogmatic',
'Although she knew the material well, the student doubted her own ability and spoke hesitantly, fearing that her answer would be foolish. Her manner was _____.','Her hesitation comes from insecurity, not careful assessment of consequences.',
'The artist’s letters repeatedly underestimate his accomplishments and express reluctance to discuss them publicly. They reveal a _____ attitude toward his own abilities.','He lacks confidence in his abilities.']
];
STRETCH.forEach(a=>WORDS.push({id:WORDS.length,word:a[0],meaning:a[1],root:a[2],distractors:a[3].split(','),variants:[{text:a[4],clue:a[5]},{text:a[6],clue:a[7]}]}));
EXTRA.necessitate='make necessary';EXTRA.infer='derive a conclusion from evidence';EXTRA.beneficial='producing a good effect';
const ROOTS = [
['cred','believe','credible','believable','credulous','too ready to believe','credible ≠ credulous: trustworthy evidence versus an overly trusting person.'],
['ver','true','veracity','truthfulness','verify','check whether something is true','Verification involves checking; it does not mean every check confirms the claim.'],
['dict','say','contradict','state the opposite','predict','say in advance','contradict is stronger than merely adding a qualification.'],
['bene','good / well','benevolent','wishing others well','beneficial','producing a good effect','An intention can be benevolent even when its effect is not beneficial.'],
['mal','bad','malevolent','wishing harm','malfunction','failure to function correctly','The prefix signals something unfavorable, but context determines the exact meaning.'],
['equ','equal','equitable','fair','equidistant','at equal distances','Equitable need not mean identical: fairness can require different treatment.'],
['ambi','both','ambivalent','having conflicting feelings','ambidextrous','able to use both hands skillfully','Ambivalent describes mixed feelings, not indifference.'],
['circum','around','circumspect','cautious','circumnavigate','travel around','circumspect: looking around before acting is a useful memory image.'],
['spect','look','retrospective','looking back','inspect','look closely at','retro means backward; the whole word still needs a context check.'],
['mut','change','immutable','unchangeable','mutable','changeable','The negative prefix changes the meaning; enduring only means lasting.'],
['luc','light','elucidate','make clear','lucid','clear or easy to understand','Clarifying a claim does not necessarily substantiate it.'],
['tract','draw / pull','intractable','hard to manage or resolve','tractable','manageable','Intractable is difficult to resolve, not necessarily impossible forever.']
];
const CONTRASTS = [
['equivocal','unequivocal','ambiguous evidence versus an unambiguous conclusion'],['qualify','refute','restrict a claim versus show it false'],['specious','plausible','misleading appearance of soundness versus apparent reasonableness'],['attenuate','eliminate','weaken versus remove completely'],['supplant','augment','replace versus add to'],['undermine','refute','weaken support versus disprove'],['ambivalent','indifferent','mixed feelings versus lack of concern'],['analogous','identical','similar in one respect versus exactly the same'],['incongruous','anomalous','does not fit its context versus departs from an expected pattern'],['plausible','substantiated','reasonable possibility versus supported by evidence'],['nuanced','equivocal','subtle distinctions versus ambiguous or inconclusive meaning'],['salient','substantial','relevance or prominence versus amount'],['sporadic','transient','irregular frequency versus short duration'],['intractable','immutable','hard to resolve versus incapable of change'],['malleable','resilient','can be reshaped versus can recover'],['mitigate','eliminate','reduce severity versus remove'],['exacerbate','precipitate','worsen an existing problem versus trigger an outcome'],['elucidate','substantiate','explain clearly versus provide supporting evidence'],['redundant','superfluous','unnecessary duplication versus unnecessary extra material']
];
CONTRASTS.push(['disinterested','indifferent','impartial judgment versus lack of concern'],['obviate','preclude','make unnecessary versus make impossible'],['repudiate','refute','reject a position versus show it false'],['erratic','sporadic','unpredictable variation versus irregular occurrence'],['diffident','circumspect','hesitation from insecurity versus caution about consequences'],['commensurate','identical','proportional to a baseline versus exactly the same'],['perfunctory','succinct','superficial routine effort versus concise expression'],['ostensible','substantiated','apparent or stated versus supported by evidence']);
ROOTS.push(
['clud / clus','close','preclude','rule out a possibility','exclude','keep out','pre- adds the idea of closing off a possibility in advance; obviate can instead remove a need.'],
['fid','trust','diffident','lacking confidence','confident','sure of oneself or a judgment','A hesitant person may be diffident; a cautious person may instead be circumspect.'],
['scrib / script','write','transcribe','make a written copy','inscription','something written or engraved','Related roots suggest writing, but ascribe means attribute, not merely write.'],
['flu','flow','superfluous','beyond what is needed','fluid','able to flow or change readily','The image of overflow is a memory cue for surplus; superfluous does not always mean repetitive.'],
['port','carry','transport','carry from one place to another','portable','able to be carried','Transfer of something is suggested; an exact sense still depends on the full word.'],
['numer','number','enumerate','list or count one by one','numeral','a symbol representing a number','Enumerating reasons lists them; substantiating reasons supplies evidence.'],
['nihil','nothing','annihilate','destroy completely','nihilism','rejection of established values or belief in inherent meaning','Annihilation is much stronger than attenuation or mitigation.'],
['hetero / homo','different / same','heterogeneous','composed of different kinds','homogeneous','uniform in kind','Diversity of composition does not automatically make elements incompatible.'],
['epi','upon / over','epidermis','the outer layer of skin','epigraph','a quotation placed at the start of a work','Prefix clues narrow possibilities, but do not establish an unrelated whole word’s meaning.']
);
if(typeof module!=='undefined') module.exports={WORDS,ROOTS,CONTRASTS,EXTRA};
