const ONEPREP_URL='https://www.oneprep.com/blog/hardest-sat-vocabulary-words-2026-75-high-frequency';
function dictionaryKey(word){return {'conjectures with':'conjecture','expound (on)':'expound','consonant to':'consonant','the former / the latter':'former','indices of':'index','pretexts for':'pretext','deferred to':'defer','intermingled with':'intermingle','tolerance for':'tolerance'}[word]||word}
const ONEPREP_WORDS=new Set('assert contend concede refute qualify underscore corroborate elucidate reconcile substantiate repudiate extrapolate postulate delineate stipulate ambivalent austere cynical sardonic wary ardent benevolent benign derisive dismissive incisive pragmatic skeptical impartial tentative explicit implicit ambiguous equivocal salient pertinent arbitrary capricious nuanced tenuous tenacious obsolete precarious viable ubiquitous aloof obsequious belligerent deferential candid egregious scrupulous meticulous indolent diligent sporadic spurious apathetic magnanimous hypothesis empirical anomaly analogy confer mitigate exacerbate constrain conflate coherent'.split(' '));
const TRENDS_URL='https://www.mrjohnstestprep.com/vocabulary-trends-from-the-last-two-years-of-official-sats/';
const TREND_TIERS={};
for(const [tier,words] of [[1,'eschew ubiquitous idiosyncratic'],[2,'abridge anomalous attenuate belie conjecture detrimental enumerate epitomize exacerbate heterogeneous incongruous index manifest preclude proponent substantiate undermine equivocal unequivocal'],[3,'abate ameliorate capacious dearth disparate evince misconstrue multifariousness pernicious precede quintessential rescind tenuous transpose underscore untenable vindicate']]) for(const word of words.split(' '))TREND_TIERS[word]=tier;
function selectionPenalty(w){if(state.focus==='all')return 0;if(state.focus==='core')return ONEPREP_WORDS.has(w.word)?0:5;if(state.focus==='corpus')return 9-Math.min(9,corpusCount(w.word)*2);return ({1:0,2:2,3:4})[TREND_TIERS[w.word]]??9}
function trendPanel(){const covered=WORDS.filter(w=>TREND_TIERS[w.word]).length;return `<div class="card section"><div class="eyebrow">REPORTED TEST TRENDS</div><h3>Source-based priority track</h3><p class="muted">${covered} covered headwords from the publisher’s highest-reported groups. Tier 1: 7–8 reported appearances; Tier 2: 4+; Tier 3: 3.</p><a href="${TRENDS_URL}" target="_blank" rel="noopener">Mr. John’s source tables ↗</a><p class="notice">Third-party reports, including recollections and some PSAT entries; not College Board-verified frequencies or future-test probabilities. The source groups equivocal / unequivocal together; the app teaches their distinct meanings separately.</p></div>`}
function evidenceRows(){return state.evidenceEntries||[]}
function personalExposure(word){return new Set(evidenceRows().filter(x=>x.word===word.toLowerCase()).map(x=>x.source+'|'+x.ref)).size}
function evidencePriority(word){const rows=evidenceRows().filter(x=>x.word===word);return Math.min(12,personalExposure(word)*2+rows.filter(x=>x.missed).length*3)}
function evidenceDue(){const seen=new Set();return [...evidenceRows()].reverse().filter(x=>{if(seen.has(x.word))return false;seen.add(x.word);return (state.evidenceMemory[x.word]?.due||dateKey())<=dateKey()}).map(x=>({word:x.word,meaning:x.meaning,root:'Source: '+x.source+' · '+x.ref+'. Your own clue: '+x.clue,evidence:true,variants:[{text:x.clue},{text:x.clue}]}))}
function evidencePanel(){return `<section class="card section" id="evidenceNotebook"><div class="eyebrow">SOURCE-TRACKED PERSONAL VOCABULARY</div><h2>Bring official mistakes into your review.</h2><p class="muted">After official practice, record the word, its contextual meaning, and the source reference. These are your observations, not an independently verified test-frequency dataset.</p><div class="twocol"><div><label for="evWord">Word or short phrase</label><input id="evWord" maxlength="80" placeholder="A word you encountered…"><label class="section" for="evMeaning">Meaning in that context (in your own words)</label><input id="evMeaning" maxlength="300" placeholder="Check the dictionary and official explanation…"><label class="section" for="evSource">Source</label><select id="evSource"><option>College Board Student Question Bank</option><option>Bluebook official practice test</option><option>Khan Academy official SAT prep</option><option>Mr. John’s reported-vocabulary quiz</option></select><label class="section" for="evRef">Question ID, or test / module / question reference</label><input id="evRef" maxlength="100" placeholder="e.g. SQB question ID or Practice test 6, RW M2 Q3"></div><div><label for="evRole">How did the word appear?</label><select id="evRole"><option value="answer">Correct answer</option><option value="distractor">Distractor choice</option><option value="passage">Passage text</option></select><label class="section" for="evClue">The decisive clue or distinction (your own explanation)</label><textarea id="evClue" maxlength="1000" placeholder="Describe the relationship; avoid pasting a whole official passage."></textarea><label class="section"><input type="checkbox" id="evMissed" checked> I missed or was uncertain about this word</label><button id="evSave" class="section">Add to spaced review</button><p class="notice">Priority combines unique source references, your mistakes, and review due dates. It measures your exposure and learning need—not the word’s probability on a future SAT.</p></div></div><div id="evidenceList" class="section"></div></section>`}
function renderEvidenceList(){const el=$('#evidenceList');if(!el)return;const words=[...new Set(evidenceRows().map(x=>x.word))].sort((a,b)=>evidencePriority(b)-evidencePriority(a));el.innerHTML=words.length?`<div class="tablewrap"><table><thead><tr><th>Word</th><th>Your observed exposure</th><th>Most recent source</th></tr></thead><tbody>${words.slice(0,30).map(w=>{const last=[...evidenceRows()].reverse().find(x=>x.word===w);return `<tr><td><strong>${esc(w)}</strong><br>${esc(last.meaning)}</td><td>${personalExposure(w)} unique question reference${personalExposure(w)===1?'':'s'}<br><small>User logged · ${evidenceRows().filter(x=>x.word===w&&x.missed).length} uncertain/missed</small></td><td>${esc(last.source)}<br><small>${esc(last.ref)} · ${esc(last.role)}</small></td></tr>`}).join('')}</tbody></table></div>`:'<p class="muted">No source-linked observations yet. Add the first word after official practice.</p>'}
function bindEvidence(){$('#evSave').onclick=()=>{const word=$('#evWord').value.trim().toLowerCase(),meaning=$('#evMeaning').value.trim(),ref=$('#evRef').value.trim(),clue=$('#evClue').value.trim(),source=$('#evSource').value,role=$('#evRole').value,missed=$('#evMissed').checked;if(!word||!meaning||!ref||!clue){notify('Add the word, contextual meaning, question reference, and your clue.');return}const entry={date:dateKey(),word:word.slice(0,80),meaning:meaning.slice(0,300),source,ref:ref.slice(0,100),role,clue:clue.slice(0,1000),missed};const old=evidenceRows().findIndex(x=>x.word===word&&x.source===source&&x.ref===ref);if(old>=0)state.evidenceEntries[old]=entry;else state.evidenceEntries.push(entry);state.evidenceMemory[word]={due:dateKey(),correct:0};const known=WORDS.find(w=>w.word===word);if(known&&missed)ws(known.id).due=dateKey();save();renderEvidenceList();notify('Added to your review queue. Duplicate references count only once.');$('#evWord').value='';$('#evMeaning').value='';$('#evRef').value='';$('#evClue').value=''};renderEvidenceList()}
function recommendationsPanel(){const covered=WORDS.filter(w=>ONEPREP_WORDS.has(w.word)).length;return trendPanel()+`<div class="card section"><div class="eyebrow">CURATED RECOMMENDATIONS</div><h3>OnePrep reading list</h3><p class="muted">The app covers ${covered} of the article’s vocabulary headwords; transitions use a separate practice mode.</p><a href="${ONEPREP_URL}" target="_blank" rel="noopener">Read the source article ↗</a><p class="notice">Recommendations without auditable counts. Source tags are not measured frequency ranks.</p><label for="priorityFocus">Question selection</label><select id="priorityFocus"><option value="corpus">Weight by collected quiz-list frequency + due words</option><option value="trends">Prioritize reported trends + due words</option><option value="core">Prioritize OnePrep recommendations + due words</option><option value="all">Explore the whole curated bank</option></select></div>`}
function bindRecommendations(){$('#priorityFocus').value=state.focus||'corpus';$('#priorityFocus').onchange=()=>{state.focus=$('#priorityFocus').value;save();notify('Question-selection preference saved. Due and source-linked words remain priorities.')}}
