// Third-party quiz target headwords only. Date is article publication date; form names
// describe the article's reported test administration. These are not College Board
// confirmed frequencies. Extracted from public flashcard/matching target lists.
const REPORTED_CORPUS=[];
const report=(title,date,form,slug,words)=>REPORTED_CORPUS.push({title,date,form,url:'https://www.mrjohnstestprep.com/'+slug+'/',words:[...new Set(words.split('|'))]});
report('The September 2026 SAT Vocab Survey + Quiz - INT Version 1','2026-09-16','September 2026 International Round 1','the-september-2026-sat-vocab-survey-quiz-int-version-1','enigmatic|rudimentary|ample|tolerance for|fraudulent|the former / the latter|ambivalent|impartial|discretion|enumerate|abundant|byzantine|lament|contest|guardedness|rescind|pragmatic|obviate|resolve');
report('The September 2026 SAT Vocab Survey + Quiz - US Version 2','2026-09-16','September 2026 US Round 2','the-september-2026-sat-vocab-survey-quiz-us-version-2','meta-analysis|fiscal|rescind|lethargic|elude|anomalous|onerous|byzantine|paradigm|preclude|perturb|epitomize|regret');
report('The September 2026 SAT Vocab Survey + Quiz - US Version 1','2026-09-16','September 2026 US Round 1','the-september-2026-sat-vocab-survey-quiz-us-version-1','periodical|lament|prevalent|implausible|debunk|polity|pragmatic|enumerate|elusive|attenuated|idiosyncratic|torpor|neglect|paradigmatic');
report('The August 2026 SAT Vocab Survey + Quiz - Int Version','2026-08-31','August 2026 International / combined new-word round','the-august-2026-sat-vocab-survey-quiz-int-version','precipitation|assuage|supplement|reconcile|abstruse|complicate|habituate|regale|tentative|nominal|imbue');
report('The August 2026 SAT Vocab Survey + Quiz - US Version','2026-08-31','August 2026 US / combined repeat-word round','the-august-2026-sat-vocab-survey-quiz-us-version','idiosyncratic|exacerbate|heterogeneous|anomalous|belie|incongruous|detrimental|rectify|portentous');
report('The June 2026 SAT Vocab Survey + Quiz - US + Int Version','2026-06-09','June 2026 US + International','the-june-2026-sat-vocab-survey-quiz-us-int-version','profusion|indecipherable|spurious|restitution|extol|consonant to|latitude|counterintuitive|inane|precarious|extrapolate|oblique|resilient|repertory|polity');
report('The May 2026 SAT Vocab Survey + Quiz - International Version','2026-05-04','May 2026 International','the-march-2026-sat-vocab-survey-quiz-international-version-2','efface|attenuate|predilection|volatile|untenable|opaque|preempt|misconstrue|incremental');
report('The May 2026 SAT Vocab Survey + Quiz - US Version','2026-05-04','May 2026 US','the-may-2026-sat-vocab-survey-quiz-us-version','repudiated|contrived|antecedence|capitulate|preclude|adhere|intransigent|vacillate|vie');
report('The April 2026 SAT Vocab Survey + Quiz - School Day Version','2026-04-06','April 2026 School Day','the-april-2026-sat-vocab-survey-quiz-school-day-version','predisposition|ephemeral|pernicious|permeate|conspicuous|unsubstantiated|anathema|incongruent|maudlin|protract|circumvent|superfluous|elide|adhere|idiosyncrasy|obsolete|incentive');
report('The March 2026 SAT Vocab Survey + Quiz - International Version','2026-03-16','March 2026 International','the-march-2026-sat-vocab-survey-quiz-international-version','haughty|cryptic|annihilate|halt|modesty|entanglement|unequivocal|multifariousness|retrospect|counterfactual');
report('The March 2026 SAT Vocab Survey + Quiz - US Version','2026-03-16','March 2026 US','the-march-2026-sat-vocab-survey-quiz-us-version','authoritative|endearing|multifariousness|pertinent|iconoclasm|refute|misconstrue|untenable|occluded|amenable|eschew|tantamount|detrimental|irrespective|substantiate|emulate|ubiquitous');
report('The December 2025 SAT Vocab Survey + Quiz - US Version','2026-01-03','December 2025 US','the-december-2025-sat-vocab-survey-quiz-us-version','belie|recapitulate|typify|promulgate|tempered|analogous|nominal|imbue|detrimental');
report('The December 2025 SAT Vocab Survey + Quiz - International Version','2026-01-01','December 2025 International','the-december-2025-sat-vocab-survey-quiz-international-version','evince|eschew|characteristic|manifest|convene|established|subtle|salvage|amalgam|apparent|contentious|transcend|heterogeneous|autonomous');
report('The November 2025 SAT Vocab Survey + Quiz - Int Version','2025-12-02','November 2025 International','the-november-2025-sat-vocab-survey-quiz-int-version','expound (on)|eschew|iconoclastic|prescient|equivocal|calculating|caricature|ambivalent|proclivity|sagacity|clandestine');
report('The November 2025 SAT Vocab Survey + Quiz - US Version','2025-12-01','November 2025 US','the-november-2025-sat-vocab-survey-quiz-us-version','emanate|implicate|delineate|entrenched|incipient|assuage|legitimize|anachronistic|abate|proliferate|idiosyncratic|nominal|indeterminate');
report('The October 2025 SAT Vocab Survey + Quiz - Int Version Round 1','2025-11-01','October 2025 International Round 1','the-october-2025-sat-vocab-survey-quiz-int-version-round-1','succession|convergence|denotes|rigor|acquiesced|oscillated|proxies|contrivance|catalysts|deterrents|abated|deferred to|intermingled with|ambivalent|opaque|meticulous|inconspicuous|extemporaneous');
report('The October 2025 SAT Vocab Survey + Quiz - US Version (Round 1)','2025-10-06','October 2025 US Round 1','the-october-2025-sat-vocab-survey-quiz-us-version-round-1','underscore|undermine|enumerate|intermingled with|indices of|redundancy|incongruence|reprisal|abridge|pretexts for|conjectures with');
report('The June 2025 SAT Vocab Survey + Quiz (Round 2)','2025-06-28','June 2025 combined Round 2 (intro inconsistently says May)','the-june-2025-sat-vocab-survey-quiz-round-2','abound|attenuate|capacious|decisive|emanate|excise|expound|heterogeneous|impervious|impugn|lambaste|outmoded|pernicious|synopsis|testament|unnerved');
report('The June 2025 SAT Vocab Survey + Quiz (Round 1)','2025-06-28','June 2025 US + International Round 1','the-june-2025-sat-vocab-survey-quiz-round-1','abate|capricious|conflate|conjecture|cursory|discerning|epitomize|eschew|exhaustive|imperious|manifest|myriad|quotidian|ubiquitous|undermine|verisimilitude|vindictive');
report('The May 2025 SAT Vocab Survey + Quiz (Round 2)','2025-06-01','May 2025 US + International Round 2','the-may-2025-sat-vocab-survey-quiz-round-2','augment|belie|burgeoning|coalesce|contentious|decouple|decry|expedite|fecund|harbinger|heterogeneity|induce|insurmountable|misconstrue|modulate|orthodox|oscillate|preclude|recapitulate|refute|steward|substantiate|supplant|unfounded');
report('The March 2025 SAT Vocab Survey + Quiz (Round 2)','2025-05-01','March 2025 US + International Round 2','the-march-2025-sat-vocab-survey-quiz-round-1-2','abridge|aggregation|amass|attenuated|attrition|contentious|corroborate|dearth|denote|detrimental|dispassionate|dissonance|emblematic|enumerate|extraneous|immoderate|impartial|intercede|invariable|nonchalance|perturbation|replicable|sentimental|supplant|transpose|visionary');
report('The March 2025 SAT Vocab Survey + Quiz (Round 1)','2025-05-01','March 2025 US + International Round 1','the-march-2025-sat-vocab-survey-quiz-round-1','abatement|diminutive|imperative|indolence|meticulous|precede|prudent|reciprocity|tranquil|ubiquitous');
report('The December 2024 SAT Vocab Survey + Quiz (Round 2)','2025-02-01','December 2024 US + International Round 2','the-december-2024-sat-vocab-survey-quiz-round-2','propagate|disquieting|sanction|wrought|copious|hypothesize|underscore|emissary|placate|incongruous|proxy|exacerbate|unsympathetic|forestalls|mutable|exploiting');
report('The December 2024 SAT Vocab Survey + Quiz (Round 1)','2025-02-01','December 2024 US + International Round 1','the-december-2024-sat-vocab-survey-quiz-round-1','mitigate|aesthetic|vindicate|elicit|commend|capitalize|eclipse|belie|augment|prevail|ascribe|idiosyncratic|ameliorate|cite|satirized');
report('The November 2024 SAT Vocab Survey + Quiz (Round 2)','2025-01-01','November 2024 US + International Round 2','the-november-2024-sat-vocab-survey-quiz-round-2','warranted|dispersed|neutral|substantiate|forsake|anomalous|subtlety|continuity|insurmountable|foster|corroborate|pretentious|appraise|substantial|monetizing|indoctrinate');
report('The November 2024 SAT Vocab Survey + Quiz (Round 1)','2025-01-01','November 2024 US + International Round 1','the-november-2024-sat-vocab-survey-quiz-round-1','heterogeneity|feasible|manifest|confounded|fraudulent|amorphous|transpose|entice|irrefutable|sophisticated|authentic|catalyzing|incongruous|reiterate|palpable|exploit');
report('The October 2024 SAT Vocab Survey + Quiz (Round 2)','2024-11-01','October 2024 US + International Round 2','the-october-2024-sat-vocab-survey-quiz-round-2','notional|earnest|misanthropic|veritable|conflate|preclude|induce|demarcation|nominal|inconspicuous|vindicate');
report('The October 2024 SAT Vocab Survey + Quiz (Round 1)','2024-11-01','October 2024 US + International Round 1','the-december-2025-sat-vocab-survey-quiz-round-1-2','discretion|nebulous|evince|ambiguous|desultory|mitigate|recalcitrant|scrupulous|placate|intercede|amass|sanguine');
report('The August 2024 US Version SAT Vocab Survey + Quiz (Round 2)','2024-09-02','August 2024 US Round 2','the-august-2024-international-sat-vocab-survey-quiz-round-2-2','nebulous|monetize|predicated|unprecedented|spurious|repudiate|precipitate|amorphous|erratic|insurmountable|outsized|predicate');
report('The August 2024 US Version SAT Vocab Survey + Quiz (Round 1)','2024-09-02','August 2024 US Round 1','the-august-2024-us-version-sat-vocab-survey-quiz-round-1','rectify|accentuate|engender|palpable|scrupulous|arduous|eclipse|augment|tally|proponents|profound|exploit|overlook');
report('The August 2024 International SAT Vocab Survey + Quiz (Round 2)','2024-09-01','August 2024 International Round 2','the-august-2024-international-sat-vocab-survey-quiz-round-2','counterfactual|conjecture|exact|omit|imitate|impart|conceivable|behold|regard|equivocal|haphazard|eccentric|unprecedented');
report('The August 2024 International SAT Vocab Survey + Quiz (Round 1)','2024-09-01','August 2024 International Round 1','the-august-2024-international-sat-vocab-survey-quiz-round-1','obliterate|accentuate|sincerity|rigor|nebulous|illuminate|esteem|rectify|arduous|novel|efficacy|apex|analytical');
const REPORTED_CORPUS_NOTES = [
 'Only dated SAT survey/quiz target lists are included; aggregate high-frequency compilations and PSAT lists are excluded to avoid double counting.',
 'A list occurrence counts presence in a third-party quiz list, not independently confirmed use on an official test. Multiple rounds/forms are separate documents, not necessarily independent test appearances.',
 'The date field records publication date from archive cards, not the test date. The form field describes the administration claimed by the article title.',
 'Source headings sometimes disagree with titles or list sizes. May2026 US/International warmups have incorrect counts; matching sections contain9. December2024 embedded headings incorrectly say2025. June2025 Round2 intro incorrectly saysMay.',
 'May2025 Round2 advertises25 but exposes24 target headwords;24 are retained. August2024 International Round2 contains a spurious placeholder entry; it is excluded, leaving13 genuine headwords.',
 'Spelling and inflections are preserved as matching-list targets. December2025 International uses amalgam, while its warmup says amalgam of. November2025 International matching spells clandestine correctly; warmup misspells it.',
 'Public HTML/text matching targets were manually checked; no answer-choice vocabulary, root examples, definitions, passages, or quiz items are reproduced.',
 'Coverage is a bounded32-document sample from August2024 through September2026. Older March/June2024 and additional2025 lists may exist; inaccessible pagination prevented a claim of completeness.'
];
if(typeof module!=='undefined') module.exports={REPORTED_CORPUS,REPORTED_CORPUS_NOTES};
