const TRANSITION_MEANINGS={consequently:'as a result',therefore:'for that reason',nevertheless:'despite what was just stated',notwithstanding:'despite',conversely:'in an opposite or contrasting relationship',moreover:'in addition',whereas:'in contrast with the fact that',hence:'therefore',thereby:'by that means',thereafter:'after that time',accordingly:'in a way appropriate to what was just stated; as a result',subsequently:'at a later time',however:'in contrast or despite that',meanwhile:'at the same time',similarly:'in a comparable way',otherwise:'under different conditions; if not',specifically:'to give a precise detail or example',instead:'as a replacement or alternative',ultimately:'in the end'};
const TRANSITIONS=[
['consequently','however,moreover,meanwhile','The instruments had not been calibrated, making their readings unsuitable for comparison. _____, the team repeated the measurements after calibration.','The invalid readings cause the need to repeat the work.'],
['therefore','nevertheless,similarly,meanwhile','The newly discovered letter was written before the supposedly earliest known account. The earlier account can no longer be considered the first; _____, the chronology must be revised.','The revision follows logically from the earlier date.'],
['nevertheless','consequently,moreover,similarly','The trial used fewer participants than planned, limiting the precision of its estimates. _____, its results were consistent with those of several larger studies.','The second statement holds despite the first limitation.'],
['notwithstanding','because of,in addition to,thereafter','_____ its modest budget, the expedition collected measurements of unprecedented precision.','The success contrasts with the financial limitation.'],
['conversely','moreover,consequently,similarly','Increasing the parameter made the simulated population more stable. _____, decreasing it made the population less stable.','The second relationship runs in the opposite direction.'],
['moreover','however,consequently,otherwise','The archive contains the author’s unpublished letters. _____, it includes the notebooks in which she planned her first novel.','The second sentence adds another type of material.'],
['whereas','because,provided that,although','The earlier map represents roads according to physical distance, _____ the later map represents them according to travel time.','The two maps are contrasted along the same dimension.'],
['hence','however,similarly,meanwhile','The two specimens have incompatible dates and cannot have originated in the same excavation layer. _____, the assumption of a common layer must be reconsidered.','The conclusion follows from incompatible dates.'],
['thereby','thereafter,nevertheless,otherwise','The editor grouped all references to the same event under a single heading, _____ making the chronology easier to follow.','The improved clarity is achieved by the grouping, rather than merely following it in time.'],
['thereafter','thereby,however,similarly','The press published the initial volume in 1912. For several years _____, it issued no further volumes in the series.','The phrase locates a period after the publication.'],
['accordingly','nevertheless,similarly,meanwhile','The laboratory learned that the old solvent could damage the samples. It revised its preservation procedure _____, choosing a solvent that avoided the damage.','The revision responds appropriately to the new information.'],
['subsequently','consequently,conversely,otherwise','The scholar completed the translation in 1980. _____, in an unrelated appointment five years later, she became director of a museum.','Only a later time is established; the text does not supply a causal relationship.'],
['however','consequently,moreover,similarly','The repair restored the painting’s surface appearance. _____, it did not resolve the structural weakness in the underlying canvas.','The unresolved weakness contrasts with the restored appearance.'],
['specifically','nevertheless,consequently,conversely','The researchers changed one feature of the protocol. _____, they increased the interval between observations from one hour to two.','The second statement identifies the exact feature changed.'],
['instead','moreover,consequently,similarly','The author chose not to describe the battle directly. _____, she portrayed its effects through the experiences of residents far from the front.','The indirect portrayal replaces the rejected direct description.'],
['otherwise','moreover,similarly,subsequently','The specimens must be stored at a stable temperature. _____, their properties may change before testing is complete.','The warning describes what may happen if the storage requirement is not met.']
].map((a,id)=>({id,word:a[0],options:[a[0],...a[1].split(',')],text:a[2],clue:a[3],meaning:TRANSITION_MEANINGS[a[0]]}));
TRANSITION_MEANINGS['because of']='as a result of';TRANSITION_MEANINGS['in addition to']='along with';TRANSITION_MEANINGS.because='for the reason that';TRANSITION_MEANINGS['provided that']='on the condition that';TRANSITION_MEANINGS.although='despite the fact that';
if(typeof module!=='undefined')module.exports={TRANSITIONS,TRANSITION_MEANINGS};
function checkTransition(correct){const q=question;session.count++;if(correct)session.correct++;today().answers++;state.transitionHistory ||= [];state.transitionHistory.push({date:dateKey(),id:q.w.id,selected,correct,confidence,seconds:Math.round(qElapsed)});save();document.querySelectorAll('[data-option]').forEach(b=>{b.disabled=true;const w=q.options[Number(b.dataset.option)];b.classList.toggle('correct',w===q.w.word);b.classList.toggle('wrong',w===selected&&!correct)});document.querySelectorAll('[data-conf]').forEach(b=>b.disabled=true);$('#prediction').disabled=true;$('#check').hidden=true;$('#feedback').innerHTML=`<div class="feedback ${correct?'':'error'}"><h3>${correct?'Connection made.':'Trace the relationship.'}</h3><p><strong>${esc(q.w.word)}</strong> — ${esc(q.w.meaning)}</p><p>${esc(q.v.clue)}</p><details><summary>Compare the connections</summary><ul>${q.options.map(w=>`<li><strong>${esc(w)}</strong>: ${esc(TRANSITION_MEANINGS[w])}</li>`).join('')}</ul></details><p class="notice">This is an Expression of Ideas exercise. It is scored separately from Words in Context.</p></div><button id="next" class="section">${nextLabel()}</button>`;$('#next').onclick=nextQuestion}
